#!/usr/bin/python

import redis
import sys

myr=redis.Redis()

if sys.argv[1] == 'list':
	print myr.smembers('derby:horses')

elif sys.argv[1] == 'del':
	for horse in xrange(2,len(sys.argv)):
		print 'deleting', sys.argv[horse]
		print myr.srem('derby:horses',sys.argv[horse])
