#!/usr/bin/python

import redis
import sys
import optparse


parser = optparse.OptionParser()
parser.add_option("-f", "--horses", type="string", dest="horsefile",
            help="file containing horses")
parser.add_option("-b", "--bettors", type="string", dest="betfile",
            help="file containing bettors")
parser.add_option("-v", "--vig", type="int", dest="vig",
            help="vig for the kids")
parser.add_option("-l", "--limit", type="int", dest="limit",
            help="bet limit per horse")
parser.set_defaults(horsefile="horses.txt", betfile="bettors.txt")
(options, args) = parser.parse_args()


myr=redis.Redis()

if not options.limit:
    parser.error('-l must be set.  see --help')

for key in myr.keys('derby:*'):
    myr.delete(key)

print myr.set('derby:betlimit', options.limit)

for horse in open(options.horsefile):
    if horse.startswith('#'):
        continue
    myr.sadd('derby:horses', horse.rstrip())

for bettor in open(options.betfile):
    if bettor.startswith('#'):
        continue
    myr.sadd('derby:bettors', bettor.rstrip())

if options.vig:
    myr.set('derby:vig', options.vig)
