#!/bin/bash

# Print a ticket for derbyday
# args: horse, bettor, amount

# This is for a Brother QL-720NW
#  uses a2ps to print more than 19 columns of text
LP="QL-720NW"

#Uncomment the next line if you don't want to print
#exit 0

if [ $# -ne 3 ]; then
	echo "Need 3 args"
	exit 1
fi

(cat <<_EOF

###################

Horse $1
Bettor $2
Amount $3

###################
_EOF

)| a2ps -P $LP --stdin="derbyday ticket"  2>&1

